### ISSUE TITLE
Add three new tags to ?Paper class and one tag to ?Author class - community curation

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/wormbase-pipeline#102]
Hi,

I'd like to propose adding three new tags to the ?Paper class and one tag to the ?Person class.

The first two are reciprocal tags that will allow us to better relate retracted publications and their subsequent retraction notices, similar to how we currently handle errata:

Retraction_in ?Paper XREF Retraction_of
Retraction_of ?Paper XREF Retraction_in

The third ?Paper and ?Person tags are to acknowledge authors who first pass their papers by having that information explicitly available in WB for display.

For ?Paper it may be beneficial to start tracking community curation more widely in WB, so perhaps a grouping tag for 'Community Curation' and then more specific sub-tags for the actual type.

?Paper
Community_curation Author_first_pass ?Person XREF Author_first_pass_curation

?Person
Community_curation Author_first_pass_curation ?Paper XREF Author_first_pass

Would something like this work?

@chris-grove - would you be interested in adding community phenotype curation tags to capture that information in WB, as well?

We can discuss more on Thursday's WB site-wide call.  I'll add an agenda item.

Thx.

**Comment by chris-grove** [comment]
@vanaukenk 
Yes, sure, that sounds good. We can discuss on tomorrow's call.

**Comment by chris-grove** [comment]
OK, based on our discussions I'll propose also adding the following tags:

?Paper
Community_curation Phenotype_curation_by ?Person XREF Phenotype_curator_for

?Person
Community_curation Phenotype_curator_for ?Paper XREF Phenotype_curation_by

I'll work with Juancarlos to update the dumping scripts so these tags should be populated automatically when dumping from the Postgres curation database.

**Comment by Paul-Davis** [comment]
cbcae4afd1de660431472cd33e86844f52d63019 closes #102
