### ISSUE TITLE
Add MobiDB features to WormBase

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#104]
InterProScan runs an analysis called "mobidblite", which predicts regions of disorder in proteins. These end up in our Ensembl db after running InterProScan. But we never read them into WormBase. 

Action: add mobidblite protein features into WormBase.

**Comment by khowe** [comment]
Copying @gw3 (as builder for WS278), but @epaule to implement. 

Suggest adding these in under the "Feature" tag in ?Protein, and will therefore need a new ?Method.

**Comment by Paul-Davis** [comment]
closed the wrong ticket

**Comment by MagdalenaZZ** [comment]
@khowe does this still need doing?

**Comment by khowe** [comment]
This ticket was assigned to @epaule back in July. I believe the work was done:

https://github.com/WormBase/wormbase-pipeline/commit/e64496283d2dd600b3413f8ea7df98a59aa2ff1a

...but needs to check that the data is in the database, is shown correctly on the website etc (the usual due diligence).

**Comment by epaule** [comment]
They are in the database and the GFF files, just don't appear on the website (outside of the treeview and JBrowse).
So i will pass on the ticket to @sibyl229 .
An example protein with mobidblite is CE00003

**Comment by sibyl229** [comment]
@khowe @epaule Can I get some clarification from you about what you want to display and where to display them? 

We have a motif details table with data drawn from the Motif_homol tag. Here is an example the existing motif details table: https://staging.wormbase.org/species/c_elegans/protein/CE29545#057--10

Is that right that these newly added features are under the Features tag and not Motif_homol tag?

**Comment by epaule** [comment]
Yes, they are predicted regions of disorder, a bit like the seg predictions for low-complexity regions. Therefore they don't have a protein domain assigned to the region, as it is more like a property and therefore in the features section.

It looks like we exclude the feature section of the proteins at the moment (probably due the low amount of information available), but I think it would be good if they would appear somewhere on the website. Historically they were in the protein domain widget, which would be an option, or maybe there is a case to create a separate table with sequence features for them.

**Comment by sibyl229** [comment]
@epaule thanks for the detailed answer! Having them in the protein domain display makes sense to me. I will ask Adam to take a look at this, since he is more familiar with this from the REST API migration.

**Comment by adamjohnwright** [comment]
@sibyl229 I will take a look

**Comment by adamjohnwright** [comment]
@epaule This took me a bit to figure out what you wanted. I think I now see what you are talking about here: https://staging.wormbase.org/species/c_elegans/protein/CE29545#73--10

In the homology widget, there is a protein_schematic diagram that does not show these "mobidblite" features. But if you click below the diagram to open up the legacy diagram you can see them there.

Luckily, as this information is in the GFF files,  I am guessing this data should be able to add in as a track in JBrowse (how the new protein schematic is generated). @scottcain do you have any thoughts on this?

**Comment by scottcain** [comment]
@adamjohnwright the mobidblite features are in the "primary" (genome) GFF3 file, but to show up in the protein schematic image, those features would have to be added to the protein GFF (like `c_elegans.PRJNA13758.WS279.protein_annotation.gff3.gz`).  There was some discussion at the time that the protein GFF was being created about adding the homology features and there didn't seem to be much interested in adding them (though, if I'm recalling correctly, it may have been a "let's do that later" sort of thing).

Those features also don't make it into the primary (chromosomal) JBrowse instance because they were never in GBrowse and nobody asked me to add them to JBrowse.

**Comment by adamjohnwright** [comment]
@scottcain I was thinking that the GFF3 file they were referring to was the primary one. It sounds like the next step is for them to add it to the Protein GFF file.

I have also not heard anyone saying that they want these features in the primary GBrowse/JBrowse

**Comment by khowe** [comment]
@scottcain they are in the protein GFF3 file for WS279:

       
acedb3[klh]1062: zcat  WS279/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS279.protein_annotation.gff3.gz | grep intrinsi | head
F30F8.2	MobiDB-lite	intrinsically_unstructured_polypeptide_region	1	21	.	.	.	Name=MobiDB-lite
F30F8.2	MobiDB-lite	intrinsically_unstructured_polypeptide_region	1	29	.	.	.	Name=MobiDB-lite
F36G9.15	MobiDB-lite	intrinsically_unstructured_polypeptide_region	44	109	.	.	.	Name=MobiDB-lite
F36G9.15	MobiDB-lite	intrinsically_unstructured_polypeptide_region	59	73	.	.	.	Name=MobiDB-lite
F36G9.15	MobiDB-lite	intrinsically_unstructured_polypeptide_region	92	109	.	.	.	Name=MobiDB-lite
Y53C10A.10	MobiDB-lite	intrinsically_unstructured_polypeptide_region	81	103	.	.	.	Name=MobiDB-lite
Y53C10A.10	MobiDB-lite	intrinsically_unstructured_polypeptide_region	81	209	.	.	.	Name=MobiDB-lite
Y53C10A.10	MobiDB-lite	intrinsically_unstructured_polypeptide_region	118	140	.	.	.	Name=MobiDB-lite
Y53C10A.10	MobiDB-lite	intrinsically_unstructured_polypeptide_region	147	175	.	.	.	Name=MobiDB-lite
C04G6.3	MobiDB-lite	intrinsically_unstructured_polypeptide_region	1	105	.	.	.	Name=MobiDB-lite

**Comment by scottcain** [comment]
Oh, well look at that.  I did a quick grep for `mobi` that came up empty, so I assumed status quo.  I'm off to update the build script and rebuild...

**Comment by scottcain** [comment]
Just to clarify my earlier comment: I jumped in mid-thread and didn't read the introductory comments, so my comment about homology is off topic.

The good news though is MobyDB-lite features have been added to the protein schematic viewer, for example: https://staging.wormbase.org/species/c_elegans/protein/CE53614#3065--10

For picking the color, I made the glyph match the purple on this page: http://old.protein.bio.unipd.it/mobidblite/ :-)

**Comment by MagdalenaZZ** [comment]
Perfect, thanks, I think we have then completed this work?
