### ISSUE TITLE
WS280 2: $WORMBASE_RELEASE parameter not set properly

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#128]
n both wormbase_ensembl module and Wormtest.pm the wormbase release version were guessed using the file $BUILD_HOME/BUILD/autoace/wspec/database.wrm in the code snippet

set filename $::env(WORMPUB)/BUILD/autoace/wspec/database.wrm

#
Get and set WormBase release number
#
set f [open $filename]
foreach line [split [read $f] \n] {
if ([regexp "NAME WS" $line]) {
regsub "NAME WS" $line "" line
setenv WORMBASE_RELEASE $line
}
}
close $f

However, at the beginning of the build, that causes an issue, because the file $BUILD_HOME/BUILD/autoace/wspec/database.wrm does not exit. The build guide even has a several-step workaround for how to create it.

There were potentially also other problems with the new testing units, which were hard to trouble-shoot and fix without messing with the build.

Action: rewrite module_ensembl to first check if WORMBASE_RELEASE is set, if not do best guess [MZ]
Modify Wormbase.pm subroutine too, to first look for the WORMBASE_RELEASE env [MZ]
Also geet previous release this way.

**Comment by Paul-Davis** [comment]
Reopen as this solution causes issues for species not in the current production run.

Standard SOP is to define $WORMBASE_RELEASE by default, that means that $WORMBASE_RELEASE always trumps the old method of using the database.wrm file to assess the build version of all species not currently being built, so while this solution works for elegans and the other species being built, it doesn't work for species older than the current build number. You end up creating bogus directories and file locations for all species in things like
