### ISSUE TITLE
WS280 3:  Check does not tally up with real values

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#129]
In this check, the results don't seem to quite tally up.

Sections of the build guide is to be updated, to be clearer. 
Run the checks for elegans and for briggsae,  and all of Mark's checks match what we would expect.

**Comment by MagdalenaZZ** [comment]
Check:  @Paul-Davis have checked the sections of the build guide around these and run the checks for briggsae and all of Mark's checks match what I would expect

-dna_headers

-split_gffs init - elegans only

-tier2_contigs init - non-elegans only

-composition

**Comment by MagdalenaZZ** [comment]
acedb3[wormbase]632: cat /nfs/production/panda/ensemblgenomes/wormbase/BUILD/briggsae/logs/run_build_tests.pl.WS280.28119
WS280 (briggsae) Build script : run_build_tests.pl -dna_headers -species briggsae -database /nfs/production/panda/ensemblgenomes/wormbase/BUILD/briggsae

Started at 210219 17:40:44
-----------------------------------

367 chromosome files found, all with headers present


-----------------------------------
Finished at 210219 17:40:45

**Comment by MagdalenaZZ** [comment]
acedb3[wormbase]788: cat /nfs/production/panda/ensemblgenomes/wormbase/BUILD/elegans/logs/run_build_tests.pl.WS280.28348
WS280 (elegans) Build script : run_build_tests.pl -dna_headers -species elegans -database /nfs/production/panda/ensemblgenomes/wormbase/BUILD/elegans

Started at 210219 17:41:48
-----------------------------------

0 chromosome files found, all with headers present


-----------------------------------
Finished at 210219 17:41:48

**Comment by MagdalenaZZ** [comment]
-split_gffs init elegans looks good /nfs/production/panda/ensemblgenomes/wormbase/BUILD/elegans/logs/run_build_tests.pl.WS280.28821  as does briggsae   /nfs/production/panda/ensemblgenomes/wormbase/BUILD/briggsae/logs/run_build_tests.pl.WS280.29083

**Comment by markquintontulloch** [comment]
The above dna headers check is showing no chromosomes as we don't normally use the species tag when running for elegans, so it's looking in the wrong directory.

**Comment by markquintontulloch** [comment]
Ignore my above comment, it's because there are no files in /nfs/production/panda/ensemblgenomes/wormbase/BUILD/elegans/CHROMOSOMES

**Comment by MagdalenaZZ** [comment]
For the script -dna_headers , I believe the more complete test is to check that the file is a complete and correct FASTA format file, with no blank lines, a header, and a sequence that contains ACGTN.
