### ISSUE TITLE
WS280 5:  No way to check the old vs new EMBL submission properly

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#130]
In the step where we do the ENA submissions, we write files to a git repository, which keeps track of which changes we do to the ENA submissions. Each submission is saved with a specific tag. We could (but we don't currently) check that compared with the last submission, the changes we do seem to make sense. Since this is data that we submit to the outside world, it could be helpful to introduce a checking step before submission.
STEP: https://www.ebi.ac.uk/seqdb/confluence/display/WORMBASE/ENA+Submissions

Build Resolution: Manual checking

cd /nfs/panda/ensemblgenomes/wormbase/analysis/submissions/elegans

#List tags

git log --decorate=full --simplify-by-decoration --pretty=oneline HEAD | \

sed -r -e 's#^[^\(]*\(([^\)]*)\).*$#\1#' \

       -e 's#,#\n#g' | \

grep 'tag:' | \

sed -r -e 's#[[:space:]]*tag:[[:space:]]*##'

# Different between last and current files

git diff WS280.1 WS279.2 --stat

# Exact difference in file

git diff WS280.1 WS279.2 --  0/V/V.embl

Action: 
1. Create a script to make a report on how many genes have changed between two saved versions, so that curators can check if that is a reasonable number [MQT]
2. Check if there are novel things in the feature table?

Expected output: Report that summarises the changes between two tagged versions, most likely the current and previous release eg. WS280.1 WS279.2, but potentially the script can also work stand-alone comparing any two versions.

**Comment by markquintontulloch** [comment]
compare_ena_submissions.pl script created and build documentation updated
