### ISSUE TITLE
WS280 10: Which files are used for xrefs? 

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#135]
It is not clear to us which files are used for xrefs, in particular for the species, like briggsae, which we don't share with EMBL. Is the data we ingest up-to-date and correct?
STEP: ENA Submissions 
perl $CVS_DIR/get_ena_submission_xrefs.pl -generatetables -species $SPECIES

Action: Go over the script, and ascertain that it does something sensible for tier2 species. If the script does not do something helpful for tier2 species, stop running it.

**Comment by Paul-Davis** [comment]
After 5 builds I think that the SOP is tried and tested enough
