### ISSUE TITLE
WS280 12: BLAST setup not working

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#136]
We are having an issue with the blast pipeline:
/nfs/production/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/ENSEMBL/scripts/worm_lite.pl error:
You must define the version of the Ensembl code that you're using either with ensembl_version (in the YAML file) or ENSEMBL_VERSION in the environment. After talking with Kevin it seems that WB and WB-parasite use different versions of ensembl, when WB-parasite were updating the version they required at the end of last year this script became incompatible with the version we use in the main WB build.

Action: Add the ENSEMBL_VERSION to the yaml config file we use or use the cloned script or just have a specific declaration in the blast SOP via setenv.

**Comment by Paul-Davis** [comment]
Would it be appropriate to add the env variable to the wormbase_ensembl module file? @MagdalenaZZ

**Comment by Paul-Davis** [comment]
Also while we are at it.....should the module file be version controlled with a local git repo?

**Comment by Paul-Davis** [comment]
Please reopen if it shouldn't be in the module file
