### ISSUE TITLE
WS280 16:  RNA and compara build guides have wrong login details 

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#138]
RNA and compara build guides have wrong login detail, referring to ebi-cli, which is some log-in node which do not exist anymore, and is automatically forwarded to noah login headnodes. 
Action: Updated RNASeq/Compara to follow the same procedure as the edited/updated blast guide.

**Comment by Paul-Davis** [comment]
The build guides were updated to match the correct noah-login procedure from other guides
