### ISSUE TITLE
Ws280 17: Interpro jobs submitted to production_rh7 which is partially deprecated

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#139]
There are several different queues to work in for LSF submission. Many queue choices are coded into the scripts, or not apparent eg. default, not explicitly set values. 
The config overrides the $LSB_DEFAULTQUEUE env variable, need to identify where this happens as the $LSB_DEFAULTQUEUE is the one we want (production_rh74). Need to review where our pipeline config files are and remove all of the clutter.

Action: 
1. Updated the base.conf to only use production_rh74
2. Checked all other scripts in the codebase to check we are always using production_rh74 queue if specified

**Comment by Paul-Davis** [comment]
All config files should have been updated to the rh74 queues
