### ISSUE TITLE
WS280  20:  ePCR executable was missing from EBI

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#142]
[KLH] copied e-PCR from Sanger to EBI 
[PD] Updated the script to use this binary
https://github.com/WormBase/wormbase-pipeline/commit/8f9277007c3e67849096130916f69bfb2f38c420

This software is deprecated, and may not be available in the future, in new OS.

**Comment by Paul-Davis** [comment]
Does this need to be kept open? or can we close it @MagdalenaZZ

**Comment by Paul-Davis** [comment]
Please re-open if you need to.
