### ISSUE TITLE
WS280 22: The file /acefiles/AGR_genes.ace contains extra double quotes

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#144]
Upon further checking, this is indeed the same synonym that is on the AGR page, so we are not creating this bug, but inheriting it. https://www.alliancegenome.org/gene/HGNC:26789
2402140 Other_name "fatty acid metabolisma"immunity nexus"

Actions:
Raised an AGR ticket and asked them to fix their synonym [MZ]
modify the AGR→Ace script to backslash weid single and double quotes in text [MQT]

**Comment by markquintontulloch** [comment]
Synonym fixed in current AGR submission.
Escaping of quotes implemented in commit [e8a9010](https://github.com/WormBase/wormbase-pipeline/commit/e8a90104a8d81f1002cc9dea594cfe9da9cbbbcf)
