### ISSUE TITLE
WS280 24:  A fair bit of genblastG failed silently

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#146]
GenBlast splits the peptides up in chunks, and then runs ~100 chunk jobs. About 1/4 th of all jobs failed. 1,2,4,12, 15, 19, 21, 23, 32, 33, 36, 38, 40, 41, 44, 48, 49, 51, 55, 61, 63, 64, 71, 72, 100.

The issue was not flagged up in the logging, but was visible in error files

So the error message shows that the process couldn't find the genome blast index: cat /nfs/production/panda/ensemblgenomes/wormbase/BUILD/briggsae/genblast/split_wormpep/wormpep_40_genome.fa.wublast
FATAL: Could not open the database
"/nfs/panda/ensemblgenomes/wormbase/BUILD/briggsae/genblast/genome/gen
ome.fa". Please check its spelling, the file access permissions, the
setting of the WUBLASTDB (or BLASTDB) environment variable, and that
the database has been processed with "xdformat" or another supported
BLAST database formatting program.
EXIT CODE 18

Have to check error messages in files to see the issue
ls -l /nfs/production/panda/ensemblgenomes/wormbase/BUILD/briggsae/genblast/split_wormpep/wormpep_4?_* /nfs/production/panda/ensemblgenomes/wormbase/BUILD/BACKUP/briggsae_279/genblast/split_wormpep/wormpep_4?_*

**Action:** 
1. Modify script to check logs, and kill the process and warn about errors if some jobs have failed.
2. Bonus: re-write the script to remove all failed files, reset the job status, and re-start the hive. 
2. Alternatively: describe in the build manual what you need to do to remove all failed files, reset the job status, and re-start the hive. 
3. Testing: is really hard, as the issue was likely caused by temporary farm instability. Running it once to see that it still executes would be good to make sure new bugs have not been introduced.
4. Testing: The old failed files are still available, if that helps at all?

**Comment by markquintontulloch** [comment]
Fixed by commits to wormbase branch of EnsemblGenomes/eg-pipelines repository [539b353](https://github.com/EnsemblGenomes/eg-pipelines/commit/539b353f14878168720bc9b07b81a45971fc4338) and [a59e196](https://github.com/EnsemblGenomes/eg-pipelines/commit/a59e1966d26856f31d3189a84e0047ac835f87b1)
