### ISSUE TITLE
WS280 25: check_class.pl do not operate on the files at the right stage

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#147]
Because check_class does tests before all data is merged in, it sometimes flags up data as missing, when it is not supposed to be added until later on.   We'd like the script to check-point against the right, comparable points in the build. We believe the right checkpoint data is preserved in the file: /net/isilon3/production/panda/ensemblgenomes/wormbase/BUILD_DATA/COMPARE/class_count.dat  and use these values to compare against

Action:  To check why the script presently is not making use of this file. Make sure the check-points are logical at the step of the build.
If it seems easy to get the script to use this file, we can change the way we call it. If not, we'll plan a proper development of this script.

**Comment by MagdalenaZZ** [comment]
Basically, like we agreed in the post-mortem @Paul-Davis will check if this is an easy fix to get the right behaviour of the software. And if it is not, we will raise a new ticket for developing the script to do the right thing.

**Comment by markquintontulloch** [comment]
The script is doing the correct thing, using the last values in the class_count.dat file.

In WS280 the check_class.pl script was run twice for the data_sets stage.  The first time it showed 10 possible errors (/nfs/panda/ensemblgenomes/wormbase/DATABASES/WS280/logs/Checked/check_class.pl.WS280.13988.gz), the second time it only showed 1 (/nfs/panda/ensemblgenomes/wormbase/DATABASES/WS280/logs/Checked/check_class.pl.WS280.20339.gz).  Judging by the log files, it appears that the first time this was run was too early in the build (before the `perl $CVS_DIR/autoace_builder.pl -misc_data_sets` stage).  @MagdalenaZZ may be able to confirm if this is the case.

The only other stage to show any potential errors was the pre-merge stage which showed 2 possible errors (/nfs/panda/ensemblgenomes/wormbase/DATABASES/WS280/logs/Checked/check_class.pl.WS280.6008.gz).

@Paul-Davis  - if the differences in class counts shown in the latter two logs make sense to you then I believe this ticket can be closed without any further action.
