### ISSUE TITLE
WS280 26: VEP output not all in GFF file

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#148]
In the GFF-style VEP output, in the aa-change field, there is an extra backslash. Column 9 is also missing some of the VEP output, like HGVSp, HGVSc and maybe also other fields that users would like to have available.

I PCoF_Million_mutation point_mutation 3646210 3646210 . + . variation=WBVar00627533;public_name=gk474960;strain=WBStrain00039111;substitution=C/T;consequence=missense_variant;aachange=E\/K
I Million_mutation point_mutation 3651349 3651349 . + . variation=WBVar00627571;public_name=gk698458;strain=WBStrain00039549;substitution=C/T;consequence=missense_variant;aachange=G\/R
I PCoF_Million_mutation point_mutation 3651349 3651349 . + . variation=WBVar00627571;public_name=gk698458;strain=WBStrain00039549;substitution=C/T;consequence=missense_variant;aachange=G\/R

The issues is caused by results returned by Table-maker query have slashes escaped so results need to be munged.  Additional VEP output fields were never added to the output as the only work done on this script was to prevent it breaking due to the changes made to the ?Variation class in the model as a result of switching to using the VEP for molecular consequences - any desired attributes can be added.

Action: 
- Changes to be made to overload_gff_variation.pl, in which backslashes removed from output of Table-maker query and all VEP fields included in column 9 output.
- Test the script is now working, by doing the GFF generation, and running the overload_gff_variation.pl script to make sure it is working as expected, and the issues are resolved.

**Comment by markquintontulloch** [comment]
Fixed by [8edbdf4](https://github.com/WormBase/wormbase-pipeline/commit/8edbdf4662ea5b20984c056b7a8272c24e4cd5c0)
