### ISSUE TITLE
WS281 Expr_pattern additions and clean-up

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#149]
Hello models, 

    I would like to add a ?Person tag in the Expr_pattern model to be  able to accommodate personal communications.

    Person? UNIQUE Person 

    I would also like to remove the Author and Date tags. Author and Date are legacy data. We discussed the issue at a Caltech call a couple of weeks ago and agreed it was fine to remove. See wiki for reference Feb 11th meeting.

    Thanks,

    Daniela 

    in the model it will look like:
```
    Experiment Laboratory ?Laboratory
                             Author ?Author
                             Date UNIQUE DateType
                             Strain UNIQUE ?Strain
                  Reference ?Paper OUTXREF Expr_pattern
                  Person? UNIQUE Person
                  Transgene ?Transgene OUTXREF Expr_pattern
```

**Comment by draciti** [comment]
@Paul-Davis I checked the models file and all looks good. Thanks for taking care of this!
Daniela
