### ISSUE TITLE
WS280 34: Add documentation for how to change FTP files

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#155]
check_manifest subroutine and make sure it is up-to-date, after we've changed the output files.

Action: Create SOP for FTP new file.

**Comment by markquintontulloch** [comment]
manifest is up to date

**Comment by markquintontulloch** [comment]
Documentation added to 'Make the FTP site' section of the build guide, describing how and when to update the manifest in make_FTP_site.pl
