### ISSUE TITLE
WS280 31:  Obo files no longer made, and species-split gene association files not produced

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#156]
Several edits to the make_GO_GAF.pl script had accidentally also messed up the other files produced by the script.
Action: Check that the obo files get produced as expected.

**Comment by khowe** [comment]
Just to point out: the Hinxton build makes GAF files, but not OBO files. The latter (containing the ontologies themselves) are provided in the Caltech upload, and we just copy them across at some point in the build.

**Comment by MagdalenaZZ** [comment]
obo-files gets copied over and renamed as expected.

**Comment by markquintontulloch** [comment]
Fixed by [8eba8f6](https://github.com/WormBase/wormbase-pipeline/commit/8eba8f6a31cec8f8be319a9f0ef2039675078d26)
