### ISSUE TITLE
WS280 39:  How do I know my trackhub has updated?

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#157]
In the end of the build, we create a trackhub database, but how can you check if your trackhub is actually live and showing on the UCSC website? The build does not really show how to test this step worked.

Action: Amend the build guide with a check for if your trackhub is actually live and showing on the UCSC website

**Comment by Paul-Davis** [comment]
**Check:** You can test the hub by connecting http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WSXXX/MULTI_SPECIES/hub/hub.txt to the UCSC browser (http://genome-euro.ucsc.edu/) after making sure you disconnected any WormBase hubs before. (My Data -> Track Hubs -> My Hubs -> add hub) URL to attach the dev hub onto the EU UCSC browser . (and the FTP sync is every hour, so it might take a while until it is accessible to the UCSC site).

This check is in the build guide is there more info needed?
