### ISSUE TITLE
WS280  40: Get non-build scripts not to write to the runlog

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#158]
Issue: Some scripts run on WS279 were not run for WS280
These scripts which are non-build are using the log module and writes to runlog.

Action: try to get non-build scripts not to write to the runlog.
That will make it possible for us to use the runlog in the future to ascertain that all steps in the build have been run.

Test: run changed scripts blank/test (if possible) and ascertain that they don't write to the runlog file

**Comment by markquintontulloch** [comment]
New method (make_build_associated_log) implemented to allow logging in build folder without writing to runlog.  Logic added to write logs of scripts run in debug mode to user-specific subfolders of log directory.  Resolved by [13b0d28](https://github.com/WormBase/wormbase-pipeline/commit/13b0d288badedd94757ff1d79f739fc2291b6bed#diff-6180b14c9c4b47812baa13b7e502a347bcf3f7733e5a893f46f749825c162411)
