### ISSUE TITLE
WS280 35: Create SOP for how to set up new users (from Admin side), and give them credentials

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#160]
In WS280 we were delayed because @MagdalenaZZ and @sdiamantakis did not have AWS user credentials which allowed them to perform all of the tasks they needed to do.
Their AWS accounts and users were eventually set up right, with all needed permissions.
Action: Create SOP for how to set up new users (from Admin side)
Test: Use the SOP to add a new users : @markquintontulloch and  make sure it works

The AWS credentials are needed for Datomic for the build for Mark (not for Name Service).

**Comment by MagdalenaZZ** [comment]
I refined the ticket a little bit now.

**Comment by mluypaert** [comment]
Instructions are now available [on Confluence](https://www.ebi.ac.uk/seqdb/confluence/display/WORMBASE/AWS+IAM+user+creation+and+permissions). I propose we create a user for @markquintontulloch and test this at the next build's migration step by having Mark do the migration? That way we can ensure the permissions are assigned as expected (in a real senario, as that's the only situation where a user will use those permissions)?

**Comment by MagdalenaZZ** [comment]
If Mark can see the ping the instance, that probably means it is all working as expected. If you want to be very fancy you could try starting/stopping it. If it helps, Mark can certainly set up or do the Datomic build in appr 4 weeks time when we get to it.
