### ISSUE TITLE
WS281 Data patch from Caltech Analysis object (Microarray)

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#168]
I had to re-annoted a microarray dataset that Igor imported years ago because he merged the experimental results. Would you read the following ace file into geneace to remove the old microarray experiments and add the new ones into the Analysis object?

Thanks and sorry for the late notice. 

Wen

/nfs/production/panda/ensemblgenomes/wormbase/BUILD/autoace/acefiles/patches/Caltech_Microarray_analysis_patch.ace

**Comment by sdiamantakis** [comment]
Patch applied on 26th
