### ISSUE TITLE
WS281 Issue 7: ENA Manual upload should not be the default

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#177]
Fix the script https://github.com/WormBase/wormbase-pipeline/blob/master/scripts/EMBLsubmit.pl so the script supports non-manual upload.
Change SOP back to automatic upload but add note to check that it worked!

**Comment by markquintontulloch** [comment]
SOP updated to use automatic process and check that upload is successful.  No changes to script required as already updated to FTPS by @khowe - removal of the manual_upload flag in the command line defaults to automatic upload.
