### ISSUE TITLE
WS281 Issue 12: database names have to be lower-case

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#179]
Action: All of our database names have to be lower case. Maybe worth a paranoid-check. Both in code that creates the database, and then accesses it later.

Action: updating SOP to use inter_pro_scan  - DONE

**Comment by markquintontulloch** [comment]
I can't see any issues with this now that the SOP has been updated.  InterPro pipeline takes database name from command line and there are no hard-coded database names in the codebase, all other WB eHive databases already use lower case names.
