### ISSUE TITLE
Molecule Model Changes - Karen

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#18]
Summary and proposed model:

http://wiki.wormbase.org/index.php/Molecule#Changes_for_WS251

As proposed following discussion and edits (Sept 4th)

```
?Molecule	Name	?Text //WBMoleculeID
	Public_name	?Text  //Source = CTD, ChEBI, research articles
	Formula ?Text //Source chebi.obo RELATED FORMULA [KEGG COMPOUND:] and RELATED FORMULA [ChEBI:] can be mulitple
	Monoisotopic_mass ?Float//Source?
	IUPAC ?Text //Source chebi.obo EXACT IUPAC_NAME [IUPAC:] can be multiple
	SMILES ?Text//Source chebi.obo RELATED SMILES [ChEBI:], unique
	InChi ?Text//Source chebi.obo RELATED InChI [ChEBI:], unique
        InChiKey ?Text//Source chebi.obo RELATED InChIKey [ChEBI:] unique
	Synonym	?Text //CTD
	DB_info	Database  ?Database ?Database_field ?Text  //for kegg/reactome pathways- also perhaps for all chebi.obo tags (may replace chebi source tags above)
	Status 	Detected  #Evidence
		Predicted #Evidence
	Origin  Plant     //from HMDB
                Microbial  ?Species
                Cosmetic
                Toxin_Pollutant
                Food_for_human
                Drug
                Exogenous
                Endogenous   ?Species #Evidence
                Drug_metabolite
                Pharmaceutical
        Biofunction //from HMDB  or ChEBI Role ontology - do we want to take in the whole ontology? can we just create the .ace and extract chebi-obo ID public name mappings/
		Metabolite //will be in ChEBI or HMDB ontology
		Regulatory //may be in ChEBI or HMDB ontology
		Structural //may be in ChEBI or HMDB ontology
	        Ligand_for Gene_product_receptor ?Gene Receptor_for_molecule #Evidence 
	        Molecule_receptor ?Molecule XREF Receptor_for_molecule #Evidence
                Receptor_for_molecule ?Molecule XREF Molecule_receptor
	        Regulate_expr_cluster	?Expression_cluster	XREF	Regulated_by_molecule
	Requirement Essential ?Species #Evidence
		    Nonessential ?Species #Evidence
	WBProcess	?WBProcess	XREF	Molecule
	Affects_phenotype_of	Variation	?Variation	?Phenotype	#Evidence
		Strain	?Strain	?Phenotype	#Evidence
		Transgene	?Transgene	?Phenotype	#Evidence
		RNAi	?RNAi	?Phenotype	#Evidence
		Rearrangement	?Rearrangement	?Phenotype	#Evidence
        Interaction	?Interaction	XREF	Molecule_interaction
	Molecule_use	?Text	#Evidence  //manual extraction from papers - should sync with ChEBI roles??
	Reference	?Paper	XREF	Molecule
	Remark	?Text	#Evidence
```

**Comment by Paul-Davis** [comment]
Error in model


Proposal:
```
            Ligand_for Gene_product_receptor ?Gene Receptor_for_molecule #Evidence 
```

"Receptor_for_molecule" is a duplicate tag within the following XREF pair in the Molecule model:
```
            Molecule_receptor ?Molecule XREF Receptor_for_molecule #Evidence
            Receptor_for_molecule ?Molecule XREF Molecule_receptor
```
Presume this is a cut and paste error?
Fix:
```
                 Ligand_for Gene_product_receptor ?Gene #Evidence 
```

**Comment by Paul-Davis** [comment]
Is this the desired structure of the model? also do you need an #Evidence on Molecule_receptor

```
          Biofunction Metabolite // will be in ChEBI or HMDB ontology
                      Regulatory // may be in ChEBI or HMDB ontology
                      Structural // may be in ChEBI or HMDB ontology
          Ligand_for Gene_product_receptor ?Gene #Evidence 
                     Molecule_receptor ?Molecule XREF Receptor_for_molecule #Evidence
                     Receptor_for_molecule ?Molecule XREF Molecule_receptor #Evidence
          Regulate_expr_cluster ?Expression_cluster XREF Regulated_by_molecule
          Requirement Essential ?Species #Evidence
                      Nonessential ?Species #Evidence
```

**Comment by kyook** [comment]
?Molecule   Name    ?Text //WBMoleculeID
    Public_name ?Text  
    Formula ?Text 
    Monoisotopic_mass ?Float
    IUPAC ?Text 
    SMILES ?Text
    InChi ?Text
    InChiKey ?Text
    Synonym ?Text
    DB_info Database  ?Database ?Database_field ?Text
    Status  Detected  #Evidence
        	Predicted #Evidence
    Origin  Plant ?Taxon
            Microbial  ?Taxon
            Cosmetic
            Toxin_Pollutant
            Food_for_human
            Drug
            Exogenous
            Endogenous  ?Taxon #Evidence
            Drug_metabolite
            Pharmaceutical
    Biofunction    	Metabolite 
        			Regulatory 
        			Structural 
    Ligand_for 	Gene_product_receptor ?Gene  Molecule_ligand #Evidence
    			Molecule_receptor ?Molecule XREF Receptor_for_molecule #Evidence
    Receptor_for_molecule ?Molecule XREF Molecule_receptor
    Regulate_expr_cluster   ?Expression_cluster XREF    Regulated_by_molecule
    Requirement Essential ?Species #Evidence
            	Nonessential ?Species #Evidence
    WBProcess   ?WBProcess  XREF    Molecule
    Affects_phenotype_of    Variation   ?Variation  ?Phenotype  #Evidence
        	Strain  ?Strain ?Phenotype  #Evidence
        	Transgene   ?Transgene  ?Phenotype  #Evidence
        	RNAi    ?RNAi   ?Phenotype  #Evidence
        	Rearrangement   ?Rearrangement  ?Phenotype  #Evidence
        	Interaction ?Interaction    XREF    Molecule_interaction
    Molecule_use    ?Text   #Evidence  //manual extraction from papers - should sync with ChEBI roles??
    Reference   ?Paper  XREF    Molecule
    Remark  ?Text   #Evidence

**Comment by kyook** [comment]
I just made some more changes to the model above.  These changes should be more intuitive and make capturing the data more straightforward.  The question remains about what the different Taxon versus Species is and if Taxon can accommodate species level annotations.

**Comment by kyook** [comment]
Paul, lets move this to WS252, there are too many things - there are still too many questions, and I need Juancarlos to make extensive changes to the postgres side of things, which won't be able to get started on for a bit.

**Comment by Paul-Davis** [comment]
Reverted models.wrm file back to the previous version with:

# Resets index to former commit; replace '56e05fced' with your commit code
git reset 008830ea34a3795c91b0d2da6d23c14aa28ad384 
# Moves pointer back to previous HEAD
git reset --soft HEAD@{1}
# Paranoia about touching multiple files
git add models.wrm
# New commit to push the rollback
git commit -m "Revert to 008830ea34a3795c91b0d2da6d23c14aa28ad384"
# Discards the working version of the file
git reset --hard 
# Pull in any changes made by others
git pull
# Pushes the changes out to the remote repo
git push

Status:  Waiting for final decisions on a couple of tags

**Comment by khowe** [comment]
The above recipe did not quite work. What we ended up doing is this:

git revert --no-commit 17a9f8fc27dcb06d024a60cae3c75c93f01faab3 wspec/models.wrm
git commit -m "Unrolled Molecule changes"

...where the referenced commit is the one that added the molecule changes. 

This model change has been deferred to WS252. Changed milestone.

**Comment by Paul-Davis** [comment]
Issue with metabolite ?Text #Evidence as majority of Metabolite data will be large scale and therefore no text comment.

Re-open ticket until change populated to models.wrm for WS252
