### ISSUE TITLE
check dbcomp.pl -pre_rel -mail_paulsternberg

### ISSUE THREAD

**Issue by sdiamantakis** [WormBase/wormbase-pipeline#189]
Some checks returning '0' eg. 'Gene_regulation', 'Mass_spec_data'
see /nfs/production/panda/ensemblgenomes/wormbase/BUILD/autoace/logs/dbcomp.pl.WS282.22025

**Comment by Paul-Davis** [comment]
Fixed with 1880676daa729c23f148be68c38ec17121aaa4dc and db6383775153777407ab7bbf16d0413ad910d9f2
