### ISSUE TITLE
Re-connect with Shohei and NBRP

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#191]
We had a script curators could use to sync Wormbase data with strain repositories, like CGC and Shigen. Of late the Shigen syncing does not work.
Shigen  https://shigen.nig.ac.jp/c.elegans/ is still active, updates new strains etc, so we need to re-start the syncing with their data.
I have reached out to Shigen asking them for advice about how to best access their data, and will update the ticket when I know more.

Goal:
There is an updated script which can regularly pull data from Shigen, and add new strains etc to our DB.

**Comment by markquintontulloch** [comment]
which script is it?

**Comment by Paul-Davis** [comment]
It's more of a broken processing pipeline with some of the scripts still being available:

**Comment by Paul-Davis** [comment]
Once upon a time in WormBase land there was a web tool that allowed Shohei to deposit his update file, this would then do lots of checks on formatting and content and once successful it would take the data and produce an series of files that could be used to update and add the data to geneace.

NBP2016_03_16update.ace
NBP2016_03_16phenotype.ace
NBP2016_03_16new.ace
NBP2016_03_16bad.ace

This service slowly degraded and the last few updates in 2019 were bodged to use a mysql database without the web front end but there was missing data.

The data is stored under: 
/nfs/production/panda/ensemblgenomes/wormbase/DATABASES/geneace/ALLELE_DATA/JAPANESE_KNOCKOUTS

I have continued/just add the files to this location and tidied up the naming a bit but the way I see it we have 2 updates from 2020 and one from March this year that we are missing and I also requested the full database but this file seems smaller than some of the "updates".

If something could be salvaged from Michael's code that would be great but we no longer have the mysql element of the old system so moving to a acedb pnly solution would be great.

**Comment by khowe** [comment]
The main rationale for Michael's system was to minimise curator intervention; Shohei would upload the file, the checks would be run immediately, and if they failed, Shohei would be told so that he could go and fix the errors. 

But maybe that is now overkill for such an infrequent and low-volume update?

**Comment by MagdalenaZZ** [comment]
If we have a script that works, we can just add it to the list of some 20 other recurring/regular curation tasks we have...

**Comment by kyook** [comment]
We had thought a long time ago to implement an automated system for creating micropublications out of Shohei’s project. Before any more development on WormBase side starts, can we revisit those thoughts. 

If we get a review panel set up for the GEP, perhaps this can also be done for the tm strains. They will be forumulatic and will live in our genomic section, we can have separate stats for them so they do not bias our output, the same with other large scale projects - like the GEP and Cotton group. 

Thoughts? 



~~~~~~~~~~~~~~~
Karen Yook
Editor - www.micropublication.org | @micropub7n
Scientific Curator - www.wormbase.org | @wormbase
skype: wbkaren





> On Aug 18, 2021, at 11:02 AM, Paul Davis ***@***.***> wrote:
> 
> 
> Once upon a time in WormBase land there was a web tool that allowed Shohei to deposit his update file, this would then do lots of checks on formatting and content and once successful it would take the data and produce an series of files that could be used to update and add the data to geneace.
> 
> NBP2016_03_16update.ace
> NBP2016_03_16phenotype.ace
> NBP2016_03_16new.ace
> NBP2016_03_16bad.ace
> 
> This service slowly degraded and the last few updates in 2019 were bodged to use a mysql database without the web front end but there was missing data.
> 
> The data is stored under:
> /nfs/production/panda/ensemblgenomes/wormbase/DATABASES/geneace/ALLELE_DATA/JAPANESE_KNOCKOUTS
> 
> I have continued/just add the files to this location and tidied up the naming a bit but the way I see it we have 2 updates from 2020 and one from March this year that we are missing and I also requested the full database but this file seems smaller than some of the "updates".
> 
> If something could be salvaged from Michael's code that would be great but we no longer have the mysql element of the old system so moving to a acedb pnly solution would be great.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

**Comment by MagdalenaZZ** [comment]
https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?pageId=149802211

**Comment by MagdalenaZZ** [comment]
Great chat with Shohei today, and we'll be trialling a new way forwards, which will hopefully make everyone happy.

**Comment by MagdalenaZZ** [comment]
NBRP updates re-established, with complete database dumps.
