### ISSUE TITLE
WS282 Issue 10 : Future FTP change Noah → Codon part 2

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#199]
The FTP site on Noah will no longer be updated, so we need to make sure we write to a space on Ace, and then copy the FTP directory over to the correct space on CODON.

1. Work out where on CODON the files need to be in order to end up on the EBI FTP site
2. Create a folder there (probably a staging area), and check that it works ie shows through to the FTP site
3. Create a new space on Ace eg next to the BUILD and BUILD_DATA folders, which can be the new "staging area"
4. Work out the commands for copying from the new staging area to CODON
5. See if it makes sense to copy over the contents of our current staging area to CODON - these files are super-important - part of the data we promise to share with people forever.

**Comment by markquintontulloch** [comment]
1.  Same location and path - will be available once switchover done
2. Cannot currently create a folder on codon as RW-only until switchover
3.` /nfs/panda/ensemblgenomes/wormbase/ftp_staging_tmp` created
4.  e.g. `bsub -n 4 -q datamover "/hps/software/copytools/msrsync/msrsync -p 8 /nfs/ebi/production/panda/ensemblgenomes/wormbase/ftp_staging_tmp /nfs/ftp/pub/databases/wormbase/releases/.WS283/"`
5. This will be taken care of by the switchover

**Comment by MagdalenaZZ** [comment]
Successfully done
