### ISSUE TITLE
WS282 Issue 10 : Future FTP change Noah → Codon part 1

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#200]
The FTP site on Noah will no longer be updated, so we need to make sure we write to a space on Ace, and then copy the FTP directory over to the correct space on CODON.

1. Make the build script write FTP folder to a different location (set up by Mark).
2.  Then update the build guide with the new instructions, including commands for copy-to-codon staging area etc.

**Comment by markquintontulloch** [comment]
New location: /nfs/panda/ensemblgenomes/wormbase/ftp_staging_tmp

**Comment by markquintontulloch** [comment]
Example command for copying files to codon (executed from codon):
` e.g. bsub -n 4 -q datamover "/hps/software/copytools/msrsync/msrsync -p 8 /nfs/ebi/production/panda/ensemblgenomes/wormbase/ftp_staging_tmp /nfs/ftp/pub/databases/wormbase/releases/.WS283/"`

**Comment by MagdalenaZZ** [comment]
Successfully done
