### ISSUE TITLE
WS283 Issue 4: check logic of $CVS_DIR/track_protein_history.pl. Output results/errors of the check only on stdout

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#204]
Errors not captured in a log, eg.

log: /nfs/production/panda/ensemblgenomes/wormbase/DATABASES/WS283/logs/track_protein_history.pl.WS283.29974.gz

WS283 (elegans) Build script : track_protein_history.pl

Started at 211017 19:47:47
-----------------------------------

Finished.

-----------------------------------
Finished at 211017 19:47:53

stdout:

T14G10.2f/CE46548 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.
Y105C5A.15c/CE50119 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.
R04B5.1/CE06212 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.
W10C8.6/CE38736 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.
T19C9.10a/CE44640 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.
B0344.2/CE33963 is in the history file as unchanged but 'wormpep283' has no record of it even in the previous version
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 132.
Use of uninitialized value in numeric eq (==) at /nfs/panda/ensemblgenomes/wormbase/wormbase-pipeline/scripts/track_protein_history.pl line 133.

Other thing is that cannot explain the logic behind those errors. Number of clones/proteins checked manually and those entries exist in wormpep283

Action: Check script and make sure error massages are written to log file, and put in extra test/skip at line 132 & 133

**Comment by Paul-Davis** [comment]
https://github.com/WormBase/wormbase-pipeline/commit/f2ca8dabc5a41f9bc5b4020cdb45d4b971c50f92
