### ISSUE TITLE
WS283 Bonus issue: GAF file testing

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#205]
Caltech sent us some GAF files with wrong content. 
Action: Create a sanity-check of the GAF files we receive, to make sure the content looks okay.

**Comment by Paul-Davis** [comment]
Correction: CalTech sent us some bad ace data that caused the GAF file when generated to be GAF complient but with bad evidence codes.

Might be good to add an accepted evidence code check to any check that are implemented.

**Comment by MagdalenaZZ** [comment]
Yes, sounds good, please do

**Comment by markquintontulloch** [comment]
Nevermind, I've worked out that the evidence codes are the GO_code tag.

**Comment by markquintontulloch** [comment]
Validation added in commit [a0ab07b](https://github.com/WormBase/wormbase-pipeline/commit/a0ab07b59680cab2dfdbf783c89e404a3b1e089b)
