### ISSUE TITLE
WS283 Issue 7: circRNA count fails in data_checks.pl.WS283.8977

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#206]
The test for circ_RNA counts fails, because the label is circular_ncRNA in gff3, but circRNA (non-SO compliant) in gff2 files.

TEST (grep GFF): circRNA circRNA (circRNAs)
ERROR: expect - 724, actual 0
STEP:  perl $CVS_DIR/autoace_builder.pl -data_check
Build Resolution: Resolved

checked manually:

$ grep 'circular_ncRNA' /nfs/panda/ensemblgenomes/wormbase/BUILD/autoace/CHROMOSOMES/*.gff3 | wc -l

724
Root cause:

data_checks.pl line 245:

$queries[$i]{'GFF'} = "circRNA\tcircRNA";

- query used for check would work for gff file but not for gff3. Query should be eg. 'circular_ncRNA'

in gff3:
CHROMOSOME_X circRNA circular_ncRNA 6095081 6095404 . + . ID=Transcript:C15H9.14;Parent=Gene:WBGene00305269;Name=Transcript:C15H9.14q
in gff
CHROMOSOME_X circRNA circRNA 6095081 6095404 . + . Transcript "C15H9.14"

GFF2 has the old non-SO-compliant "circRNA" instead of the newer "circular_ncRNA"
Permanent resolution:

Action(s): 

Solution 1 (preferred):
First: Check with Scott that he doesn't use the gff2 [PD]
1. Make sure both GFF2 and GFF3 files are written with the SO-compliant "circular_ncRNA" label.
2. Update the test in the file to look for the right label

Solution 2:
Update the test in the file to look for the right label in GFF3 files

**Comment by scottcain** [comment]
I don’t use GFF2, and it looks like circular RNA are present in 283’s JBrowse:
https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=X%3A6094879..6095607&tracks=Polymorphisms%2CCurated_Genes%2CCurated%20Genes%20(noncoding)&highlight=

**Comment by Paul-Davis** [comment]
Thanks @scottcain, the wider OICR tools, do these all use the gff3? we would like to spec up the gff2 source feature to better follow the gff3 to make consistency checking easier.

**Comment by Paul-Davis** [comment]
8b09421ec3b4ad156a8f59207225926cdae02f80

**Comment by scottcain** [comment]
As far as I know, nothing on the website uses gff2, but I'll tag @tharris to double check.
