### ISSUE TITLE
WS283 Issue 9:   write_DB_remark.pl.WS283.24382 error

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#207]
An error is reported by the script 

20:36:40: Processing transcript class
ERROR: Bm1_00005A does not have a Gene tag. This is bad!

This is not error and was ignored in previous builds.

We believe this is not an error, and would like to change the script so that it maybe produces a warning instead?

**Comment by Paul-Davis** [comment]
This commit https://github.com/WormBase/wormbase-pipeline/commit/30b2d378d09225af21cc2af840b339cb2fd8fc81 should have resolved the issue, but this is old??

Testing it now

**Comment by Paul-Davis** [comment]
resolved with https://github.com/WormBase/wormbase-pipeline/commit/0e79d998de1f85eb7612aec5f5919af1b400cffe
