### ISSUE TITLE
EMBL-dump codon test very odd results

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#212]
Some features/fragmants are lost in the new EMBL dump on codon

```
Chromosome I

FT   precursor_RNA   7954977..7955033
FT                   /gene="mir-8209"
FT                   /locus_tag="CELE_T22C1.13"
-FT                   /standard_name="T22C1.13"
-FT                   /product="pre-microRNA mir-8209"
-FT   prim_transcript 7954820..7955081
-FT                   /gene="mir-8209"
-FT                   /locus_tag="CELE_T22C1.13"
FT                   /standard_name="T22C1.13.1"
FT   ncRNA           7954977..7954997
FT                   /gene="mir-8209"
FT                   /locus_tag="CELE_T22C1.13"
FT                   /standard_name="T22C1.13a"
FT                   /product="microRNA mir-8209,a"
FT                   /ncRNA_class="miRNA"
FT   ncRNA           7955012..7955033
FT                   /gene="mir-8209"
FT                   /locus_tag="CELE_T22C1.13"
FT                   /standard_name="T22C1.13b"
FT                   /product="microRNA mir-8209,b"
FT                   /ncRNA_class="miRNA"
```

nother non-miRNA example

```
FT   CDS             complement(join(9692701..9692790,9692838..9693558,
FT                   9693692..9693781))
<FT                   /gene="C04F12.6"
<FT                   /locus_tag="CELE_C04F12.6"
<FT                   /standard_name="C04F12.6"
<FT                   /note="Curated pseudogene"
<FT                   /pseudogene="unknown"
<FT   tRNA            9679644..9679718
FT                   /gene="C04F12.t1"
FT                   /locus_tag="CELE_C04F12.t1"
```

2 features skipped/merged
```
FT   CDS             12698904..12699200
-FT                   /gene="F28C12.8"
-FT                   /locus_tag="CELE_F28C12.8"
-FT                   /standard_name="F28C12.8"
-FT                   /note="Curated Pseudogene"
-FT                   /pseudogene="unknown"
-FT   tRNA            7842914..7842988
-FT                   /gene="F30F8.t1"
-FT                   /locus_tag="CELE_F30F8.t1"
-FT                   /standard_name="F30F8.t1"
-FT                   /note="Predicted tRNA pseudogene pseudogene"
-FT                   /pseudogene="unknown"
-FT   rRNA            15060299..15061150
 FT                   /gene="rrn-3.56"
 FT                   /locus_tag="CELE_F31C3.10"
 FT                   /standard_name="F31C3.10"
```

Lines like this are corrected
```
-FT                   /note="Predicted tRNA pseudogene pseudogene"
+FT                   /note="Predicted tRNA pseudogene"
```

**Comment by Paul-Davis** [comment]
It seems to be a character limit so these methods/FTs are effected

FT   tRNA_Pseudogene^^1041553..1041623
15
FT   prim_transcript^^complement(14656500..14656636)
15
FT   rRNA_Pseudogene,15060299..15061150
15

I have it fixed:

* I have truncated all the offending EMBL_features in the test build database, misc_autoace_methods (for WS284 build)
* Modified EMBLdump.pl script to substitute the FT values back to their correct assignment so that the resulting EMBL files have: 
* a) Valid feature table tokens
* b) Annotations are identical to the original WS283 files apart from the date.

**Comment by Paul-Davis** [comment]
@khowe would be interested to see if you have any thoughts on what systems architecture might influence the whitespace padding in dump files from acedb?

**Comment by khowe** [comment]
@Paul-Davis the Acedb EMBL dumping code does this:

  /* write feature key and location */
  fprintf (dumpFile, "FT   %-16s", featText) ;

This means that the feature key is always 16 characters, with whitespace padding added for feature names that are shorter than 16. Your offending feature names above are all 15 characters. This should result in a single char of whitespace at the end (which is what we see in all of our old EMBL dumps). 

So what exactly are you seeing in the codon dumps?
