### ISSUE TITLE
EMBLsubmit.pl - Net:FTPSSL error

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#213]
So it seems Net::FTPSSL IS available on codon :tada:, but it looks like something isn't up to the current security spec. anyone have any ideas what this is and how to resolve?

```
ERROR: Cannot connect to webin.ebi.ac.uk: SSL connect attempt failed error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
Cannot connect to webin.ebi.ac.uk: SSL connect attempt failed error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
SSL connect attempt failed error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small	...propagated at /hps/software/users/wormbase/shared/gitrepos/wormbase-pipeline/scripts/Log_files.pm line 238.
 at /hps/software/users/wormbase/shared/gitrepos/wormbase-pipeline/scripts/Log_files.pm line 238.
	Log_files::log_and_die(Log_files=HASH(0x36db5c8), "Cannot connect to webin.ebi.ac.uk: SSL connect attempt failed"...) called at /homes/pad/wormbaseGIT/wormbase-pipeline/scripts/EMBLsubmit.pl line 161
```

Tried to specify SSL versions but couldn't resolve

Manual upload will work as the connection details cxan be used to manually drop the update.

**Comment by markquintontulloch** [comment]
SSL settings have changed between noah and codon.  An SSL config file was created with the appropriate settings and pointed to using the OPENSSL_CONF environmental variable, which now gets exported upon loading the wormbase_ensembl module.
