### ISSUE TITLE
WS285 Expression cluster tag addition - Single_Cell_RNASeq

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#222]
I'd like to add the tag "Single_Cell_RNASeq" to the Expression Cluster schema. It should be placed under "Attribute_of"

?Expression_cluster Description ?Text                                       // refers to Biological meaning of this cluster group
                     ...
                    Attribute_of Microarray_experiment ?Microarray_experiment XREF Expression_cluster
                                 Mass_spectrometry ?Mass_spec_experiment XREF Expression_cluster
                                 RNAseq ?Analysis XREF Expression_cluster_RNAseq
                                 Single_Cell_RNASeq //Wen WS285 for CenGen data
                    ...

-- 
Wen Chen, Ph.D.
Scientific Analysis, WormBase

**Comment by MagdalenaZZ** [comment]
The tag should instead be: Single_Cell_RNASeq ?Analysis XREF Expression_cluster_scRNASeq //Wen WS285 for CenGen data

**Comment by MagdalenaZZ** [comment]
Tested in Ace, and seems to work
