### ISSUE TITLE
Two new “Association types” for Ranjana

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#223]
Two new “Association types” between a model and a disease have been discussed and agreed upon by the Alliance disease and phenotype working group. This works very well with the way WormBase curates and relates to genetic modifiers of disease and was actually advocated for by us 

This change should be non-controversial for other data types/models and should not affect them. 

Also--we can take the opportunity to clean up some tags that haven’t been used in a long time, these tags should have no data associated with them.

The additions (and deletions) requested are:

?Disease_model_annotation	Association_type	UNIQUE	is_model_of
												is_implicated_in
												is_marker_for
												is_ameliorated_model_of 	—> new tag for WS285
												is_exacerbated_model_of 	—> new tag for WS285
												causes_or_contributes_to_condition  —> remove tag
												causes_condition				   —> remove tag
												contributes_to_condition			  —> remove tag

**Comment by rankishore** [comment]
@MagdalenaZZ I checked the WS285 models file for the above tag requests and it looks good. Thanks.
