### ISSUE TITLE
WS285 remove tags from Expression class model

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#224]
Hello,
I would like to remove a couple of tags from the gene expression model. 

To remove:
Pseudogene ?Pseudogene OUTXREF Expr_pattern
Protein ?Protein OUTXREF Expr_pattern
Protein_description Text
MovieURL Text
Laboratory ?Laboratory

Thanks,

Daniela

**Comment by MagdalenaZZ** [comment]
Tested, and seems to work
