### ISSUE TITLE
WS284 Issue 8 ENA submission file is not preserved after uploading

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#225]
Submission file is created in a temporary directory. It seems that it would be worth to keep this file.

As for now SKD updated the guide with an advice to manually copy this file to /nfs/production/flicek/wormbase/wb/BUILD/autoace/MISC_OUTPUT

We want to instead automatically copy this file in the script

**Comment by sdiamantakis** [comment]
added Back up submission file in  https://github.com/WormBase/wormbase-pipeline/commit/efab7095dfa61e0cd7298875fa984874f0e36824
