### ISSUE TITLE
?Phenotype_info Affected_by Pathogen

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#23]
Tag addition to capture if a Phenotype is observed in the presence of a Pathogen

Curator Note: The intended purpose is to capture phenotypes that are influenced by the
presence of, or exposure to, various pathogenic organisms.

<pre>
?Phenotype_info
                Affected_by  Molecule  ?Molecule  #Evidence
                             Pathogen  ?Species   #Evidence
</pre>

**Comment by chris-grove** [comment]
@Paul-Davis 

 Just to be clear, the "Pathogen" tag is intended to be a sub-tag of the "Affected_by" tag. I think the text formatting may not have captured that adequately on my first request.

**Comment by Paul-Davis** [comment]
@chris-grove thanks, yes I was going to add it there, but white space doesn't transfer well between media :(

Updated

**Comment by chris-grove** [comment]
@Paul-Davis  OK, yeah, I figured as much. Thanks!
