### ISSUE TITLE
anatomy_ontology.obo file creation_date field is wrong

### ISSUE THREAD

**Issue by sdiamantakis** [WormBase/wormbase-pipeline#233]
As reported in Paulo  in Slack #build285

[Paulo Nuin](https://app.slack.com/team/U09NR5HHS)  [21:48](https://wormbase.slack.com/archives/C03AV2Q9M51/p1654634931551069)

There's an issue, at least for WormMine build, on the anatomy_ontology.obo file
[21:49](https://wormbase.slack.com/archives/C03AV2Q9M51/p1654634962599979)
`
[Typedef]
id: RO:0017001
name: utilizes
def: "X utilizes Y means X and Y are material entities, and X is capable of some process P that has input Y." []
property_value: IAO:0000112 "A diagnostic testing device utilizes a specimen." xsd:string
property_value: IAO:0000117 "Asiyah Lin" xsd:string
property_value: IAO:0000117 "https://orcid.org/0000-0001-9625-1899 Bill Duncan" xsd:string
property_value: IAO:0000232 "A diagnostic testing device utilizes a specimen means that the diagnostic testing device is capable of an assay, and this assay a specimen as its inpu$
property_value: IAO:0000232 "See github ticket https://github.com/oborel/obo-relations/issues/497" xsd:string
holds_over_chain: RO:0002215 RO:0002233
-->> creation_date: 2021-11-08
`
[21:50](https://wormbase.slack.com/archives/C03AV2Q9M51/p1654635015486849)
It seems that the creation_date field is wrong as it needs hour, minutes and seconds too. I deleted the line from my source as it is not required for WormMIne

**Comment by MagdalenaZZ** [comment]
I'll raise this in website instead
