### ISSUE TITLE
QC for Laboratory class

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#249]
Early on in the build, add a coded/manual QC step to check that all Laboratory entries look okay: the name is 2-3 characters long, all caps, and has content (eg people or address associated with it). 

The problem we encountered before was that there were entries which were empty, and clearly not valid lab designations, for example DOIs, hyperlinks, numbers... These are all fixed now (hopefully), but it has apparently been a recurring problem.

Simplest; the script can report the suspect labs in the log file, for the builder to deal with. More fancy; create a patch file deleting the entries, which the builder can apply, after reviewing.

**Comment by markquintontulloch** [comment]
I've added a check to the Wormtest module.  It generates a patch file to remove dubious Laboratory objects.  It can be run as follows:
`bsub -I -M 4000 -R'select[mem>4000] rusage[mem=4000]' -q production perl $CVS_DIR/run_build_tests.pl -lab_check <ace_patch_filepath>`
@sdiamantakis or @MagdalenaZZ - can you add this to the appropriate point in the SOP as I'm not sure at which point it is best to carry out this check.  This ticket can then be closed.

**Comment by sdiamantakis** [comment]
Tested and done for WS287.
Added this check to the Build Guide (to the block of checks after autoace_builder.pl -first_dumps -gff_dump init step).

Details:
Tested on WS287 between Database to literature mapping and Feature mapping steps.
Test creates valid ace file containing 35 lab objects to remove.
Checked manually in autoace before loading patch: it contains 35 ghost (bogus) Lab objects.
Loaded bogus_labs_fix.ace (all good) and manually checked in autoace: all bogus lab objects gone.

@markquintontulloch   "Can't call method "set" on an undefined value" seems to be harmless this time but if you want, have a look at this. I think it's just an empty line causing that.

```
Job <3962574> is submitted to queue <production>.
<<Waiting for dispatch ...>>
<<Starting on hl-codon-126-02>>
Using /nfs/production/flicek/wormbase/wb/DATABASES/WS286
ERROR: No data attached to laboratory 'XTL'
ERROR:
**** WARNING: 35 errors identified by run_build_tests.pl ****


**** WARNING: 35 errors identified by run_build_tests.pl ****

Can't call method "set" on an undefined value at /hps/software/users/ensembl/ensw/C8-MAR21-sandybridge/plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/Ace.pm line 234, <GEN
1> line 1.
        ...propagated at /hps/software/users/wormbase/shared/gitrepos/wormbase-pipeline/scripts/Log_files.pm line 238.

```
Log file is fine: /nfs/production/flicek/wormbase/wb/BUILD/autoace/logs/run_build_tests.pl.WS287.342559

If nothing else needs to be done than we can close it.
