### ISSUE TITLE
?Feature model change for Transcription Factor::Feature connectivity.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#25]
Hello,

I would like to propose a small change to the Feature model in order
to accommodate the addition of more than one Transcription_factor

Current model:

?Feature
Transcription_factor UNIQUE ?Transcription_factor XREF Binding_site

Proposed change:

?Feature
Associations Associated_with_transcription_factor ?Transcription_factor XREF Associated_feature #Evidence

Thanks,

Mary Ann

**Comment by Paul-Davis** [comment]
Need to make corresponding tag in Transcription_factor class

**Comment by epaule** [comment]
had a side effect on GFF munging. Fixed in b86cbc58ee9819d2e4118edaa0acc64d1e364bfa
