### ISSUE TITLE
?GO_annotation model change for WS296

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/wormbase-pipeline#271]
Hi @sdiamantakis 

If there is still time, I'd like to propose a slight change to the ?GO_annotation model.
I would like to change the ?Text field for each Annotation_extension relation to be ?RO_term.  
Juancarlos and I are updating the parsing script for the new annotation files we get from GO and UniProt and all of the values for this field are now RO_terms.

All of the ?Text field in the model would be changed to ?RO_term:

![image](https://github.com/user-attachments/assets/31a48dfd-b0ea-45b6-bf83-3e3ff72ac26c)

Thank you!

@azurebrd

**Comment by sdiamantakis** [comment]
Hi Kimberly @vanaukenk, No problem, but I think it would be worth to mention this on All HAnds tomorrow so others are in the loop too.

**Comment by sdiamantakis** [comment]
new model files created,
tested on test database (just indexing) - no errors returned
pushed to GitHub

**Comment by vanaukenk** [comment]
Many thanks @sdiamantakis @markquintontulloch
