### ISSUE TITLE
Distributed passwd.wrm file contains EBI/sanger usernames

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#30]
It would probably be nice to not include real usernames in the password file distributed on the ftp site(s).

**Comment by Paul-Davis** [comment]
This should resolve the issue 4aa05aee4da8d94fb3388af02f7d326c5f58cb1d under testing.

**Comment by MagdalenaZZ** [comment]
I believe only user names are still in the file, not any passwords, so potentially that is a fairly okay conclusion to this issue?
