### ISSUE TITLE
MosDEL Production_method in ?Variation class

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#32]
I would like to propose a new Production_method tag within the ?Variation model.

MosDEL
```
Origin Production_method MosDEL
```
Thanks,

Mary Ann

**Comment by Paul-Davis** [comment]
Should the Production_method be UNIQUE @tuli 

Thanks

**Comment by tuli** [comment]
@Paul-Davis 
Yes the Production_method should be unique.
