### ISSUE TITLE
geneace Vars contain stale Build data

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#37]
Variations:
If you do a query:  Find variation where Predicted_CDS 
You retrieve 134 results
If you do a query:  Find variation where Transcript
You retrieve 33 results
From the ones I looked at, these are produced by map_Alleles.pl (evidence) so should only be populated during the build to make sure the CDS exists.

**Comment by tuli** [comment]
Where are you looking? Geneace?

**Comment by Paul-Davis** [comment]
yes

**Comment by tuli** [comment]
It should be fine to remove all these connections with confidence. So I have! 

All, apart from 18 of them (Transcript ones) are from an un-suppression event e.g. gk2273 (see Remark), where I guess the data was dumped out of current_DB and loaded into Geneace.
