### ISSUE TITLE
models.wrm.annot missing from release distribution

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#43]
The file is missing in the `wspec` directory when the release tarball is unpacked.

**Comment by mgrbyte** [comment]
I think [this](/WormBase/wormbase-pipeline/blob/234d74a9f69851cc72d42636330daf58574ba6dd/scripts/build_release_files.pl#L96) is one place where is needs added, not sure if there's any more.

**Comment by khowe** [comment]
Fixed code for WS257. Put the file in by hand for WS256. File will be in acedb/models.wrm.WS256.annot

**Comment by mgrbyte** [comment]
I can see that the annotated models *does* get put on the FTP site already: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS256/acedb/

I was expecting it to exist within the tarball (inside the wspec directory where it exists in the git source)

**Comment by khowe** [comment]
No, it's there because I just put it there!

**Comment by khowe** [comment]
Actually, I'm not quite sure though why it's not in the wspec in the tarball. Investigating...

**Comment by khowe** [comment]
Right, found it. The script make_release_files.pl has a specific list of files in wspec that it puts into the tar ball. It does not know about that annotated model file. 

I can change the script, but wondering: should the annot file be part of the tar ball? I'm thinking it might be better kept outside the tar ball.

**Comment by mgrbyte** [comment]
I think it's probably not relevant for users who download the tarball generally.
It's fine to pull it from the release directory on the FTP server as you've coded.
thanks!

**Comment by mgrbyte** [comment]
Opened a [ticket](WormBase/db-migration/issues/8) for fixing this for the db-migration.
