### ISSUE TITLE
Rename tag in Splice_confirmation hash model

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#45]
The `#Splice_confirmation` class has the following tag:

`False ?Sequence`

I'd like to determine what this is used for (if anything) 

It's causing me problems when processing the migrated model, and ideally would like to rename it (and any other tag names that resolve to [clojure.core](https://clojure.github.io/clojure/clojure.core-api.html) symbols)

AFAICT, the `#Splice_confirmation` hash model is not used anywhere (references to it are all commented out in the models.wrm.annot file)

**Comment by Paul-Davis** [comment]
Basically this is where an intron is seen in sequence data that turns out to be false.....we only have 2 sequences that use Confirmed_intron which is the root of the branch that uses this hash so I think this can be reomove from the models completely once I've deleted the data.

**Comment by Paul-Davis** [comment]
I'll remove it from the .anno file as acedb does try and do some display function in the xace FMap.

This is already commented out in the .anno file is this still an issue @mgrbyte ?

**Comment by Paul-Davis** [comment]
The #Splice_confirmation is still used in the Feature_data class but never the "False" attribute.

**Comment by mgrbyte** [comment]
@Paul-Davis commented lines in the .annot file are not being processed, but the definition of the hash-model is - thus the conversion code will create a schema in datomic for the hash-model `#Splice_confirmation` (defined on line ~1472 in the models.wrm.annot file)

**Comment by Paul-Davis** [comment]
This bit you commented out?
Line - 1474-1484

```
// Unused (mgrbyte)
// #Splice_confirmation cDNA ?Sequence // ?Sequence link to flag which cDNA is confirming
//                      EST ?Sequence  // or falsifying the intron in question, added [031121 krb]
//                      OST ?Sequence
//                      RST ?Sequence
//                      RNASeq ?Analysis Int
//                      Mass_spec ?Mass_spec_peptide
//                      mRNA       ?Sequence
//                      Homology ?Text
//                      UTR ?Sequence
//                      False ?Sequence
//                      Inconsistent ?Sequence
```

**Comment by mgrbyte** [comment]
@Paul-Davis Sorry, yes... I've alrady changed it and committed to master (had a local copy of the annot file and confused myself).... sorry for the noise :see_no_evil:

**Comment by Paul-Davis** [comment]
lol no problem :)
