### ISSUE TITLE
Revisit the OMIM disease data pipeline via ensembl as OMIM do provide the data

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#46]
Last time I ran the pipeline there were issues with how we use the e! code and various dependency issues

**Comment by khowe** [comment]
Might want to change the script to get the human gene -> disease mappings directly from NCBI:

ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/mim2gene_medgen

However, the human gene ids are NCBI accessions, whereas we deal in Ensembl id currency. So this might actually complicate matters.

**Comment by Paul-Davis** [comment]
Thanks...I will take a look.

**Comment by Paul-Davis** [comment]
This looks to all be redundant and resolved by the use of the WBParasite compara and ortholog list.
