### ISSUE TITLE
GPI file for GO

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#47]
We need to start producing a GPI file with each build. This is critical for dataflow with GO. 

Format is described here:

http://www.geneontology.org/page/gene-product-information-gpi-format

May need further discussion (e.g. what to do about UniProt isoform ids)

**Comment by khowe** [comment]
An example: 

http://wiki.geneontology.org/index.php/LEGO_August_8,_2016#NEO_Overview_and_GPI_Files

**Comment by khowe** [comment]
UniProt worm example:

ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/WORM/goa_worm.gpi.gz

**Comment by epaule** [comment]
small prototype:

`#!/usr/bin/env perl
use Ace;

my $db = Ace->connect(-path => shift);
my $genes = $db->fetch_many(-query => 'Find Gene;Species="Caenorhabditis elegans";Live') or die(Ace->error);

print "!gpi-version: 1.2\n";

while (my $g = $genes->next){
   # Gene block
   printf "WB\t%s\t%s\t%s\t%s\tgene\ttaxon:%i\t\t%s\n", 
       $g,
       $g->Public_name,
       ($g->Concise_description||$g->Provisional_description),
       join('|',$g->Other_name),
       $g->Species->NCBITaxonomyID,
       join('|',uniprot_xref($g)
   );
   foreach my $t($g->Corresponding_CDS){
    # Transcript/CDS block
    printf "WB\t%s\t%s\t%s\t%s\ttranscript\ttaxon:%i\t\%s\t%s\n", 
       $t,
       $g->Public_name,
       $t->Brief_identification,
       '',
       $t->Species->NCBITaxonomyID,
       "WB:$g",
       join('|',uniprot_xref($t)
    );
    foreach my $p($t->Corresponding_protein){
       # Protein block
       printf "WB\t%s\t%s\t%s\t%s\tprotein\ttaxon:%i\t\%s\t%s\n", 
       $p,
       $g->Public_name,
       $p->Gene_name,
       '',
       $p->Species->NCBITaxonomyID,
       "WB:$g",
       join('|',uniprot_xref($p)
    );
 
    }
   }

}

sub uniprot_xref{
  my ($object)=@_;
  my @results;
  map{
     push(@results,"$_:${\$_->right(2)}");
  } $object->at('Identity.DB_info.Database');
  return @results;
}`

**Comment by epaule** [comment]
do you know someone at the "consumer" side that would be willing to see if it work for them? As I think we name the xrefs differently, etc.

**Comment by epaule** [comment]
I put an example of how the WB GPI looks here:
ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/STAFF/mh6/test.gpi.gz
I added the ncRNA genes/transcripts, so there now some genes with mixed
RNAcentral/UniProt xrefs, due to gene having coding and non-coding
isoforms. SO-term for the ncRNAs were pulled through their Method ->
SO_term connection

Can you have a look?
