### ISSUE TITLE
Policy Change when a classically defined gene is identified on the genome.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#49]
Traditionally when a gene is finally cloned the data on the Sequence based gene is transferred to the classically defined WBGene object, primarily for convenience as this involves moving the least amount of data, but this is not good for data provision to static/infrequently updated 3rd party/canonical resources such as the C. elegans canonical proteome.

**Propose merging the other way round.**

Discussion lifted from team Slack.

Kevin Howe [12:09 PM] 
This is an important topic. In the post-post-genomic era, it might make sense to merge uncloned into cloned - because messing around with the WBGene ids of the canonical protein set causes more trouble than messing around the with WBGene ids associated with genetic information (like CGC names). Perhaps.

Kevin Howe [12:13 PM] 
@maryann.tuli well yes - the policy that the uncloned gets gene precedence is, I believe, a facet of classical C. elegans genetics. (edited)

Mary Ann Tuli [12:13 PM] 
You are correct.

Kevin Howe [12:14 PM] 
But we are now in a genomics world. And from a genomics point of view, it causes few asynchrony problems (in my view) if the cloned gene takes precedence.

[12:15]  
How many genetics-oriented papers refer to WBGenes anyway? Hardly any, I bet.

[12:15]  
(and as you say, the merge history is there for people to go digging if they wish)

Mary Ann Tuli [12:15 PM] 
It's fine, I don't disagree. Maybe no discussion needed.

Kevin Howe [12:16 PM] 
Well, if we propose to change > 20 years of policy, I would argue that discussion *is* needed!!

[12:17]  
What would be the practical consequences? If we merged uncloned into cloned, we would need to make sure that all of the genetic info from the uncloned gene (including the GCG name) got transferred across. Do have a process in place to do that?

Paul Davis [12:17 PM] 
The ?Gene class hasn't been around that long.

**Consequences of this policy change:**

Discussion with wider audience (Tim and the rest of the consortia)
Script change/new script to manage efficient data transfer.

**Comment by tuli** [comment]
@Paul-Davis stated "primarily for convenience as this involves moving the least amount of data,"
This was not the main reason, it was more that it was felt that it was preferable to retain the WBid of the gene object which had the CGC name. I don't have a strong case to keep doing it this way.

It has always been the preferred direction, but doing it the other way is also fine and didn't break anything. 

I do merges manually as 1) there aren't many of them and 2) I do like to be sure all data ends up where it should be. It could be scripted though. 

The main work involves Orthologs (transferring (or not!) to the new Live gene - I often dump the object out and loads as .ace files if there are more than one or two. The orthlog name update can be done by script.

**Comment by Paul-Davis** [comment]
Did we decide if this was going to be the new way of doing merges? I noticed that there was one going the other way during the WS259 prep.

**Comment by tuli** [comment]
Not yet discussed (cos you were doing your allotment last week).

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved, if not, please re-open.
