### ISSUE TITLE
Ace dumping: The cache1 is full

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#50]
The warning message sometimes ends up in Ace dumps. We filter it out in the primary dumps at the start of the build. But it also needs to be filtered out in the merge dumps at the end of the build.

**Comment by Paul-Davis** [comment]
Which data class had grown to the point of triggering this annoying acedb bug?

**Comment by khowe** [comment]
It was Feature_data in brugia that triggered the problem in WS258

**Comment by epaule** [comment]
I see it quite often in the B.malayi curation database.

**Comment by khowe** [comment]
Although weird: I'm looking now, and the same code is used for dumping and processing primary and merge. 

Struggling to see why "The cache1 is full" was not filtered out for merge when it is for primary.

**Comment by epaule** [comment]
stupid question: would it affect @mgrbyte m as he is dumping from ACeDB for the Datomic build?

**Comment by khowe** [comment]
@epaule - potentially, yes.

**Comment by epaule** [comment]
I had a look in the current_db dumps that I did yesterday, and I couldn't spot any cache1 errors in it.

I also don't get it when opening the FMap for Bm74 with WS257 and WS258, but it appears in BUILD/brugia and brugia_curation.

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved. If not, please let me know.
