### ISSUE TITLE
suspicious identifiers found in datomic all_classes_report

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#53]
I'm trying to fix the "qa" report that's done as part of the migration.
The code I have still produces dodgy looking counts as shown in the attached report where the Added and Missing columns shown non-zero values.

[WS257-report.pdf](https://github.com/WormBase/wormbase-pipeline/files/776938/WS257-report.pdf)

During my analysis to find the discrepancies, I came across these:
##  Control characters in identifiers (lots found here, so output omitted)
```bash
grep -E ".*\\\.*" all_classes_report.WS258.txt
```
Most are escaping a semi-colon (`\;`) or a forward slash (`\/`),
in fact, there are only two entries that are not doing so:
```bash
grep "\\\\" all_classes_report.WS258.txt | grep -vE '(\;|\/)'
```
```
Paper : ""WBPaper00029148\n\"
Sequence : "[cgc5513]:Y39A3CL\""
```
## Questions
1. Is the escaping of semi-colons and forward slashes due to the way the perl script writes the output,
    or are those escaping characters *actually* in the identifier string?
2. What should we do about it?

## Feature request
Additionally, I'd be nice for the db-migration side, if this file format could be changed to output 
in a standard format (e.g csv, json), instead of the current custom format.
e.g: csv of the form (2 columns):
  `"ClassName", "IdentifierValue"`

Would enable the use of standard parsing library instead of writing custom code.

N.B: all_classes_report is the gunzipped ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS258/REPORTS/all_classes_report.WS258.txt.gz

**Comment by gw3** [comment]
The malformed WBPaper is in the Variation WBVar00143737 - Mary Ann has 
been notified so she can take a look.

I can't see where the RNAi Sequence is coming from.

Gary

**Comment by epaule** [comment]
that RNAi is from 2003, added by Igor to citace. It probably should not have the quotation mark in the end of the identifier.

**Comment by epaule** [comment]
i punted it in direction of Chris

**Comment by gw3** [comment]
Matt:
The escaping of unusual characters happens when the ace file is dumped 
out by tace. The escaping characters are not *actually* in the 
identifier string.
I'll change the script that dumps out the datomic qa all_classes report 
to your suggested CSV format.
Gary

**Comment by mgrbyte** [comment]
@gw3 That's great that those things are not *actually* in the identifiers :smiley: 
Will the dumping script be able to right tace's wrongs w/regards to the escaping?
Thanks!

**Comment by gw3** [comment]
It's simple to just remove the back-slashes from the output.
I'll do this in a minute.
I'm just checking through the output to find more examples of malformed 
ID before I remove their backslashes...

Stuff like this looks suspect:

"Author", "HE\/Baillie"
"Author", "RKH\/LA"
"Author", "Sule &Ccedil\;ataltepe"
"Author", "Zenteno-Savi\;n T"

I'll post a full list later

Gary

**Comment by mgrbyte** [comment]
I'm curious; do we know what inserts those `\;`?

**Comment by gw3** [comment]
@mgrbyte you might like to try using: ftp://ftp.sanger.ac.uk/pub/wormbase/STAFF/gw3/all_classes_no_backslash.dat.gz

**Comment by mgrbyte** [comment]
file doesn't seem to exist there :question:

**Comment by epaule** [comment]
it syncs only once every 20 minutes

**Comment by gw3** [comment]
@mgrbyte patience . . .  .   .     .       .

**Comment by epaule** [comment]
The authors come from CalTech papers, as they got Kimberly in their timestamps.
I think their tokenizer doesn't like special characters

**Comment by epaule** [comment]
I think that is fixed by now
