### ISSUE TITLE
Move all WBsfs into the database containing the genome.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#54]
For a long time WBsf data has been split between the seqdbs and geneace.

For the purposes of curation I believe one beneficial option would be to move all of this data centrally into the organism sequence database. This will allow curators to can view and update these features as an when they are reviewing a CDS/Transcript/Pseudogene or incorporating new data sets without having to load/delete large feature datasets when the curation databases are produced.

The only drawbacks I can see are:

1) Camace will be bigger and more unwieldy 
2) Mary Ann will need access to a sequence database if she wants to curate WBsfs
3) We will need a checking script to make sure Features where the gene association is not calculated automatically are kept connected to live genes.

Anyway, please discuss.

Paul

**Comment by Paul-Davis** [comment]
Additional Stats for genece Features:
406972 TOTAL
401493 - TSS/TES_regions
2430 - enhancer
1979 - binding_site
528 - TF_binding_site
277 - Genome_sequence_error
95 - promoter
73 - regulatory_region
74 - History
23 - features created via XREF from Gene

**Comment by tuli** [comment]
To be clear then, you are talking about benefits to you and Gary, NOT all curators who work with Sequence Feature data. Is that right? 

The problem is that I curate seqfeats in geneace and you don't know about them. Right?

Apart from Killing/Merging the seqfeats don't really impact on the other work I do in geneace ie having them not in geneace isn't a problem. 

It has been proposed that 1) either all Features are moved to camace and then when I make new Features in Geneace, we can move these before each Build.

Or 2) we make a copy of camace for you to curate Features in.

If 1) does it mean that all seqfeats would be in both geneace and camace? 

If 2) Why a copy, could I not curate directly in camace? 

I actually don't really mind, there are so few of them anyway.

**Comment by tuli** [comment]
For point 2) in the original post - I curate seqfeats in geneace, but have a copy of the fmap (from currentDB) in order to get the flanks.

**Comment by khowe** [comment]
@tuli are you planning on coming into campus any time soon? It would be good to discuss this together in person. I'm open minded about the best solution.

**Comment by tuli** [comment]
@khowe I can come in on Friday until about 1.15pm
Yes, be good to discuss in person.

**Comment by Paul-Davis** [comment]
Sorry, for some reason I didn't get notifications of your comments, but to answer your questions.

The benefits would be for all curators as the main benefit is to have them centrally so that we don't have duplication/conflict in data and can view them in the genomic context automatically with the most up to date mappings rather than having multiple databases open. The major issue at the moment is that large scale feature data has been loaded into geneace and so are not visible on the genome in the sequence curation databases as we don't dump and load this datatype from geneace

New features would be made in the corresponding organism sequence db, No new features would be curated in geneace

canonical camace vs curation database......better to just add a user to the curator list  as we used to do when Ant had a copy. That way we don't have to worry about write access or anyone being delayed by another curator.

**Comment by Paul-Davis** [comment]
@tuli did you manage to discuss this with @khowe when you came in last week?

**Comment by tuli** [comment]
No, we were waiting for you.

**Comment by Paul-Davis** [comment]
oh :(

**Comment by tuli** [comment]
It's ok, I'll come in again soon!

**Comment by Paul-Davis** [comment]
S this hasn't moved on since I initially raised it.......I have cleaned up the overlap between the 2 databases and documented what features should be stored where:

https://www.ebi.ac.uk/seqdb/confluence/display/WORMBASE/Feature+Types

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved bu Paul. If not, please let me know.
