### ISSUE TITLE
Annotated models: review/re-model application of evidence/hash-models on enums   

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#61]
@Paul-Davis @khowe
Currently, the annotated models attempts to apply hash models to tags marked up with `ENUM`.
This does not translate, and the actual data is not (and cannot be) kept during the conversion process.

The following regexp will find all such occurrences: `ENUM.*#[A-Za-z]+`
e.g:
#Molecular_change Nonsense

**Comment by Paul-Davis** [comment]
I think that for #Evidence we can lose some:

?Gene Status UNIQUE ENUM ^status Live #Evidence - 5 instances so could be removed all curator_confirmed

for others it might be more tricky

Where it is an alternative # such as #GR_condition this is a much bigger issue.

```
?Gene Status UNIQUE ENUM ^status Live #Evidence
Regulation_result ENUM Positive_regulate #GR_condition
Status UNIQUE ENUM ^status Live #Evidence
Type UNIQUE ENUM ^type Coding_pseudogene ^coding #Evidence
Copy_status UNIQUE ENUM ^status Full #Evidence
Variation_effect ENUM Gain_of_function_undetermined_type #Evidence
Maternal UNIQUE ENUM Strictly_maternal #Evidence
Ease_of_scoring UNIQUE ENUM ES0_Impossible_to_score #Evidence
Type    ENUM ^type Journal_article #Evidence
Status UNIQUE ENUM Live #Evidence
Mating_efficiency  Male ^male-mating-efficiency ENUM UNIQUE ME0_Mating_not_successful #Evidence
                                       Hermaphrodite ^hermaphrodite-mating-efficiency ENUM UNIQUE HME0_Mating_not_successful #Evidence
                    Nonsense UNIQUE ENUM Amber_UAG Text #Evidence
                    Splice_site UNIQUE  ENUM Donor Text #Evidence
          Status ENUM Detected #Evidence
          Biofunction_role ENUM Metabolite ?Text #Evidence
```

**Comment by mgrbyte** [comment]
@Paul-Davis could you provide an id/object reference/query for something that has some GR_condition data so I can verify that it's actually not been converted? 
I *think* I was wrong about this, and the data is being converted.

**Comment by Paul-Davis** [comment]
There are 3885 Interactions that use this # here are the 1st few.

```
KeySet : "GR_condition.ace"
Interaction : "WBInteraction000003092"
Interaction : "WBInteraction000003154"
Interaction : "WBInteraction000003155"
Interaction : "WBInteraction000003177"
Interaction : "WBInteraction000003178"
Interaction : "WBInteraction000003179"
Interaction : "WBInteraction000003212"
Interaction : "WBInteraction000003228"
Interaction : "WBInteraction000003268"
Interaction : "WBInteraction000003295"
Interaction : "WBInteraction000003331"
Interaction : "WBInteraction000003393"
Interaction : "WBInteraction000003408"
Interaction : "WBInteraction000003409"
Interaction : "WBInteraction000003412"
Interaction : "WBInteraction000003413"
Interaction : "WBInteraction000003414"
Interaction : "WBInteraction000003415"
Interaction : "WBInteraction000003416"
Interaction : "WBInteraction000003443"
Interaction : "WBInteraction000003860"
Interaction : "WBInteraction000004090"
Interaction : "WBInteraction000004099"
Interaction : "WBInteraction000004100"
Interaction : "WBInteraction000501384"
Interaction : "WBInteraction000501386"
Interaction : "WBInteraction000501387"
```

**Comment by mgrbyte** [comment]
Myself and @Paul-Davis tracked down the particular issue with regard to the `ENUM` construct in the annotated models. Conversion fails only when there is an `ENUM` of the following forms:

`ENUM SomeName ?SomeRef  #SomeHash`
`ENUM SomeName TextUsually #SomeHash`

This has been an issue when developing the datomic rest-api, in particular attempting to get paper evidence from the enumerated value of biofunction-role via molecule entities.
See [here][1]
 
All other existent usage of  `ENUM` in the conversion process seem to work.
i.e Evidence data is converted in the common case:
`ENUM SomeName #EvidenceOrSomethingElse`

[1]: https://github.com/WormBase/website/issues/5687

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved. If not, please let me know about it.
