### ISSUE TITLE
Need copy of GPI and GAF files in per-species annotation directories on FTP site

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#62]
In make_FTP, we need to make a copy of the GO GAF and GPI files in the g_species/bioproject/annotation folder. This will ensure the creation of a symlink to the latest versions of these files that does not contain the release number

The files should be called:

G_SPECIES.BIOPROJECT.RELEASE.gene_product_info.gpi.gz
G_SPECIES.BIOPROJECT.RELEASE.go_annotations.gaf.gz

**Comment by khowe** [comment]
Suggest that the GPI file is simply moved from its current place into the annotation folder; and the GAF file(s) are kept in the ONTOLOGY folder, but we make copies in the per-species annotation folders.

**Comment by khowe** [comment]
@epaule Reminder that this needs to be in place for WS261 (which starts on Monday)

**Comment by epaule** [comment]
is the gene_associations file the same as you go_annotation one?

**Comment by khowe** [comment]
@epaule Yes. 

Source: ONTOLOGY/gene_association.WS260.wb.c_elegans
Destination: species/c_elegans/PRJNA13758/annotation/c_elegans.PRJNA13758.WS260.go_annotations.gaf.gz
