### ISSUE TITLE
Release letter - add assembly information

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#63]
Need a table of assembly information in the release letter for each core species.

**Comment by epaule** [comment]
`#!/usr/bin/env ruby

require 'json'

json = File.read(ARGV.shift)
obj = JSON.parse(json)

cols = ['appeared_in','assembly_accession','assembly_name','bioproject','bioproject_description','is_canonical','laboratory']
puts "species\t"+cols.join("\t")
obj.each_value{|v|
  v['assemblies'].each{|a|
       puts v['full_name']+"\t"+cols.collect{|tag|a[tag]}.join("\t")
  }
}`

**Comment by khowe** [comment]
Should also add UCSC names to Sequence_collections (and ASSEMBLIES.json)

Sequence_collection : "Genome:C_elegans-WBcel235"
DB_info Database UCSC assembly_name "ce11"

Sequence_collection : "Genome:C_elegans-WBcel215"
DB_info Database UCSC assembly_name "ce10"

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved. If not, please let me know about it.
