### ISSUE TITLE
tkcurate.pl - If using Isoformer CDS keep evidence 

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#64]
Hi,

Would be neat if the "Isoform" option could recognise when an Isoformer CDS is used and keep the Isoform evidence and remark etc. as this is fuller information than the straight Isoform creationg meta data.

![isoformer_cds](https://user-images.githubusercontent.com/717707/28575314-7b6abb34-7148-11e7-8ae2-07dc4cc4db6f.png)

**Comment by MagdalenaZZ** [comment]
I believe this issue has not been resolved, and will not be resolved. If this is not the case, please let me know about it.
