### ISSUE TITLE
Remove redundant Genetic Interaction Tags

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#69]
In WS261 we added the new modules for genetic interaction data capture, it was agreed that for 2 cycles the old tags would persist to allow rollback to the old method of data storage. These duplicate tags need cleaning up in the WS263 cycle.

**Comment by Paul-Davis** [comment]
#58

**Comment by Paul-Davis** [comment]
Pushing this to WS264 as it's just tag removal and I want to freeze the models for caltech testing today and would like to clarify with Chris before stripping the tags

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved. If not, please let me know about it.
