### ISSUE TITLE
Disease_model_annotation new tag "Modeled_by_remark"

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#71]
New tag to be used for capturing remarks like ‘Human Abeta variant was expressed in worms’ or some such detail.  For now we don’t have objects to express this human genetic entity. Most MODs are using ‘notes’ fields to capture this. 

```
Modeled_by Modeled_by_remark ?Text
```

**Comment by Paul-Davis** [comment]
@mgrbyte could you test the models.wrm.annot file for this change pls 👍

**Comment by mgrbyte** [comment]
[schema262-modeled_by_remark-test.txt](https://github.com/WormBase/wormbase-pipeline/files/1284980/schema262-modeled_by_remark-test.txt)
This converts cleanly. resultant schema:
```
   [modeled-by-remark :string :indexed :many]
```

**Comment by Paul-Davis** [comment]
yeah that looks good :) thanks for testing it

**Comment by Paul-Davis** [comment]
Curator went for the opposite option to what I thought, adding UNIQUE in final model file version.

**Comment by Paul-Davis** [comment]
@mgrbyte I've tweaked the file again to make the new tak UNIQUE, I don't envisage any issues but I guess you would like to test the full conversion on the latest tagged version:

https://raw.githubusercontent.com/WormBase/wormbase-pipeline/models.wrm.WS262/wspec/models.wrm

Thanks

**Comment by Paul-Davis** [comment]
Closed by 3078bea399792c6d42dae293605a79b834daa006

**Comment by mgrbyte** [comment]
Re-tested, all fine :+1: 
Diff for your latest change vs the first test:
```
-   [modeled-by-remark :string :indexed :many]
+   [modeled-by-remark :string :indexed]
```

**Comment by Paul-Davis** [comment]
Ta.....so are we happy the WS262 .annot stands up to testing or do we need to do more? I'm still not 100% what pre flight checks we can do :)
