### ISSUE TITLE
Brugia Uncloned Pseudogenes

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#72]
Why do we have these in the database?

Gene WBGene00269465 // had a biotype of SO:0000336
Gene WBGene00269468 // had a biotype of SO:0000336
Gene WBGene00269469 // had a biotype of SO:0000336
Gene WBGene00269470 // had a biotype of SO:0000336
Gene WBGene00269474 // had a biotype of SO:0000336
Gene WBGene00269480 // had a biotype of SO:0000336
Gene WBGene00269488 // had a biotype of SO:0000336
Gene WBGene00269495 // had a biotype of SO:0000336
Gene WBGene00269499 // had a biotype of SO:0000336
Gene WBGene00269504 // had a biotype of SO:0000336
Gene WBGene00269560 // had a biotype of SO:0000336
Gene WBGene00269620 // had a biotype of SO:0000336
Gene WBGene00269622 // had a biotype of SO:0000336
Gene WBGene00269625 // had a biotype of SO:0000336

Uncloned pseudogenes and should we assign a biotype?

**Comment by epaule** [comment]
They are historical ones from JDH. Their location is not clear from the excel file she sent. @Paul-Davis
