### ISSUE TITLE
generate_disease_class.pl relies on a file dating from 2012 needs an update

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#74]
$CVS_DIR/lsfsubmit.pl -m 4 perl $CVS_DIR/generate_disease_class.pl

Requires OMIM flat file (pre-downloaded into MISC_STATIC) 
/nfs/wormpub/BUILD_DATA/MISC_STATIC/omim.txt

**Comment by MagdalenaZZ** [comment]
If this is still an issue, please re-open this ticket.

**Comment by epaule** [comment]
that has been replaced with the human_disease.WSXYZ.ace.gz from promote_omim_data.pl .
