### ISSUE TITLE
Anatomy function hash text reassignment proposal

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#75]
The conversion of leaf tags that are themselves data with an optional Text field has the consequence of loosing the leaf tag and therefore data. It is proposed to remove the ?Text field in this instance as this appears to be optional additional information about the leaf tag qualifier that has been selected.

Current Model:
```
#Anatomy_function_info Autonomous Text
                       Nonautonomous Text
                       Sufficient Text
                       Insufficient Text
                       Necessary Text
                       Unnecessary Text
                       Remark Text
```

Proposed:

```
#Anatomy_function_info Autonomous
                       Nonautonomous
                       Sufficient
                       Insufficient
                       Necessary
                       Unnecessary
                       Remark UNIQUE Text
```

The Remark Text could be a structured single Text field where the linkage to the leaf tag could be echoed

Associated issue: https://github.com/WormBase/datomic-to-catalyst/issues/142

**Comment by Paul-Davis** [comment]
Done in the .wrm and .annot files

**Comment by raymond91125** [comment]
I'm concerned with Remark UNIQUE Text. If I want to say Autonomous + some remark && Sufficient + other remark, how would it work? What happens if they are entered at different times?

**Comment by Paul-Davis** [comment]
Concerns addressed and a new model submitted.
