### ISSUE TITLE
Review third party protein sets used in different areas of WS production.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#77]
Currently we use different protein sets for Compara and Blast. Night be good to standardise in the future.

**Comment by MagdalenaZZ** [comment]
I believe this issue has been resolved. If not, please let me know about it.

**Comment by epaule** [comment]
It kind of hasn't been resolved, as it was a plan to replace our bespoke protein sets with as example UniProt (or maybe some future AGR protein set).
