### ISSUE TITLE
[WBPS] Sort out gff_sources for a species in .yaml config

### ISSUE THREAD

**Issue by wbazant** [WormBase/wormbase-pipeline#83]
`ENSEMBL/lib/WormBase2Ensembl.pm` does this:
```
next if defined $source_hash and not exists $source_hash->{$l[1]};
```

`worm_lite.pl` does this:
```
my $source_hash;
    if ($config->{gff_sources}) {
      $source_hash = {};
      foreach my $source (split(/,/, $config->{gff_sources})) {
        $source_hash->{$source} = 1;
      }
    } else {
      $source_hash = { WormBase => 1, WormBase_imported => 1 };
    }
```

As a result you need to *always* check what the gff's source column contains, make it right, or else have no data, which is a sad, sad state of affairs.

TODO
`defined $source_hash` -> just check $source_hash in a boolean context

```
my $source_hash = {};
foreach my $source (split(/,/, ($config->{gff_sources} // ""))) {
    $source_hash->{$source} = 1;
}
```
on hold until I get wiser and find out what happens with that source column later.

**Comment by khowe** [comment]
Not sure I'm convinced by this one. With the current code, if you specify an explicit list of sources in config, it will only process lines with those sources (and ignore the rest). If you do not specify an explicit list of sources (default), it will only process lines with WormBase/WormBase_imported source. 

Therefore, by default, giving any old external GFF file to the loader will result in no features being extracted. I believe this is correct. Most/all external GFF files will contain a mixture of different types/sources of feature, some we want to import, and some we do not. The default behaviour (no data) forces you to look at the file, think about which subset of it we wish to import, and configure appropriately.

**Comment by khowe** [comment]
Also: many GFFs contain multiple gene prediction sets (discriminated by source), and we very rarely want to import all of them by default.
