### ISSUE TITLE
map_alleles - mis-classification?

### ISSUE THREAD

**Issue by khowe** [WormBase/wormbase-pipeline#87]
WBVar00000038 is an insertion allele. Looking at the mapped coords, a largish segment of DNA is inserted into an intronic region. However, map_alleles says:

Intron
Coding_exon

for transcript F31E8.2a. 

Needs looking at.

**Comment by Paul-Davis** [comment]
I have corrected the flanks to be blunt ended with the 11bp of unique sequence between the tandem copies of the genomic sequence. Couldn't verify so added a remark to the WBVariation object to be cautious and PCR if needing validation.
