### ISSUE TITLE
Annotated models: Gene_class Other_name/Main_name mapping

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase-pipeline#98]
Hi @Paul-Davis 

ATM there's this cyclic mapping in the annotated models, which looks like it will cause the importer to disregard data tag (because the things point to each other - need to double-verify this...) 
https://github.com/WormBase/wormbase-pipeline/blame/master/wspec/models.wrm.annot#L249-L250

The converter does not convert `Other_name`, but retains `Main_name`.

Possibly related to #93.

Other instances of the same INXREF/OUTXREF-pointing-to-each-other pattern exist in annotated models; e.g: `?Anatomy_term`  class, `Male_origin` and `Male_fate`.
Similarly, the converter doesn't keep `Male_fate` tag in this case.

**Comment by Paul-Davis** [comment]
There are indeed cyclical XREFs in multiple classes

#93 moves to standardise and fix one pair of these tags, now

Other_name XREF Other_name_for

![other_name_for](https://user-images.githubusercontent.com/717707/54025642-0e741f80-4193-11e9-8d7d-2f3daa80865b.png)

Are you suggesting that we should double store the data

**Comment by mgrbyte** [comment]
@Paul-Davis no suggestion, just an observation.
This aspect of the models markup always confuses me; to me it suggests that data will be dropped every time I see this pattern! :wink:

**Comment by Paul-Davis** [comment]
What would happen in the exporter if you did have a cyclical scenario and used the OUTXREF OUTXREF on both sides?

**Comment by mgrbyte** [comment]
:thinking:  attribute would be dropped would be my expectation. We can try it if you like? :slightly_frowning_face:
